from modeling.backbone import resnet, xception,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          mobilenet

from modeling.backbone import mobilenet_3f
def build_backbone(backbone, output_stride, BatchNorm, in_channels=3):
    if backbone == 'resnet':
        return resnet.ResNet50(output_stride, BatchNorm)
    elif backbone == 'xception':
        return xception.AlignedXception(output_stride, BatchNorm)
    elif backbone == 'mobilenet':
        return mobilenet.MobileNetV2(output_stride, BatchNorm, in_channels=in_channels)
    elif backbone == 'mobilenet_3f':
        return mobilenet_3f.MobileNetV2(output_stride, BatchNorm, in_channels=in_channels)
    else:
        raise NotImplementedError
